name: Continuous Deployment

on:
  push:
    branches: [ master ]

jobs:
  build-readme-file:
    runs-on: ubuntu-latest
    steps:
      # Checkout, install tools..
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: npm run lint
      # Save files.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[ci skip] Automatic file changes/fix'
          branch: 'master'
          file_pattern: ':/*.*'
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

  build-docker-image:
    needs: build-readme-file
    runs-on: ubuntu-latest
    steps:
      # Checkout, install tools..
      - uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0

      # Set up QEMU for multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the Docker image for multiple platforms
      - name: Build and push the Docker image (multi-platform)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/starcub/how-to-cook:latest \
            --push .